<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GlobalPagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pages = [
            [
                'name' => 'Terms',
                'url' => 'terms',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'Yes',
                'is_editable' => 'Yes',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 1,
            ],
            [
                'name' => 'FAQ',
                'url' => 'faq',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'Yes',
                'is_editable' => 'Yes',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 2,
            ],
            [
                'name' => 'Blog',
                'url' => 'blog',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'Yes',
                'is_editable' => 'Yes',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 3,
            ],
            [
                'name' => 'Sign in',
                'url' => 'sign-in',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'Yes',
                'is_editable' => 'Yes',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 4,
            ],
            [
                'name' => 'Sign up',
                'url' => 'sign-up',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'Yes',
                'is_editable' => 'No',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 5,
            ],
            [
                'name' => 'Email verify',
                'url' => 'email-verify',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'No',
                'is_editable' => 'No',
                'status' => 'Active',
                'page_in_menu' => 'No',
                'sorting' => 0,
            ],
            [
                'name' => 'Password Reset',
                'url' => 'password-reset',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'Yes',
                'is_editable' => 'No',
                'status' => 'Active',
                'page_in_menu' => 'No',
                'sorting' => 0,
            ],
            [
                'name' => 'Password Set',
                'url' => 'password-set',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'Yes',
                'is_editable' => 'No',
                'status' => 'Active',
                'page_in_menu' => 'No',
                'sorting' => 0,
            ],
            [
                'name' => 'New Order',
                'url' => 'new-order',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'No',
                'is_editable' => 'Yes',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 1,
            ],
            [
                'name' => 'Mass Order',
                'url' => 'mass-order',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'No',
                'is_editable' => 'Yes',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 2,
            ],
            [
                'name' => 'Orders',
                'url' => 'orders',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'No',
                'is_editable' => 'No',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 3,
            ],
            [
                'name' => 'Services',
                'url' => 'services',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'Yes',
                'is_editable' => 'Yes',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 4,
            ],
            [
                'name' => 'Drip Feed',
                'url' => 'drip-feed',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'No',
                'is_editable' => 'No',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 5,
            ],
            [
                'name' => 'Add Funds',
                'url' => 'add-funds',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'No',
                'is_editable' => 'Yes',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 6,
            ],
            [
                'name' => 'Child Panels',
                'url' => 'child-panels',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'No',
                'is_editable' => 'Yes',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 7,
            ],
            [
                'name' => 'Subscriptions',
                'url' => 'subscriptions',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'No',
                'is_editable' => 'No',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 8,
            ],
            [
                'name' => 'Affiliates',
                'url' => 'affiliates',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'No',
                'is_editable' => 'Yes',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 9,
            ],
            [
                'name' => 'Tickets',
                'url' => 'tickets',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'No',
                'is_editable' => 'Yes',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 10,
            ],
            [
                'name' => 'API',
                'url' => 'api',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'No',
                'is_editable' => 'No',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 11,
            ],
            [
                'name' => 'Account',
                'url' => 'account',
                'content' => '',
                'meta_title' => '',
                'meta_keyword' => '',
                'meta_description' => '',
                'is_public' => 'No',
                'is_editable' => 'No',
                'status' => 'Active',
                'page_in_menu' => 'Yes',
                'sorting' => 12,
            ],
        ];

        DB::table('global_pages')->insert($pages);
    }
}
